//! Property tests for the parts of the engine where a wrong answer is plausible
//! and hard to see: the VLQ decoder, the attribution accounting and the path
//! join.
//!
//! These are deliberately written against the *public* API rather than reaching
//! into internals. A unit test can assert that `decode_vlq` returns what the
//! author believed the spec said; only a test that builds a real map and checks
//! the bytes adds up can catch the spec being misremembered - which is exactly
//! the bug that shipped once (bytes after the last mapping were dropped).
//!
//! proptest rather than cargo-fuzz: it runs on stable, needs no nightly
//! toolchain, and a CI that cannot run the fuzz target will not run it. The
//! properties are narrow and deterministic, which is what makes a failure
//! reproducible from the seed in the panic message.

use omnibundle_core::fusion::suffix_match;
use omnibundle_core::model::{
    Asset, Chunk, Module, Severity, SizeDimension, SizeSet, UnifiedBundleGraph,
};
use omnibundle_core::sizes;
use omnibundle_core::sourcemap::parse_bytes;
use proptest::prelude::*;

const B64: &[u8; 64] = b"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";

/// Encode one signed VLQ value, as the source map v3 spec defines it.
fn vlq(value: i64) -> String {
    let mut v = if value < 0 { ((-value) << 1) | 1 } else { value << 1 };
    let mut out = String::new();
    loop {
        let mut digit = usize::try_from(v & 31).unwrap_or(0);
        v >>= 5;
        if v > 0 {
            digit |= 32;
        }
        out.push(B64[digit] as char);
        if v == 0 {
            return out;
        }
    }
}

/// A map where each source owns one segment, laid out at a known offset.
///
/// Sources are named so that the path join is exercised too: a map writes
/// `webpack://ns/./src/x.ts` and stats writes `./src/x.ts`.
///
/// The declared generated length is deliberately *not* a parameter: it is not
/// part of a source map document, so the caller passes it to
/// `attribute_by_source_in` instead, which is the API under test.
fn map_with_segments(offsets: &[u32]) -> Vec<u8> {
    use std::fmt::Write as _;

    let sources: Vec<String> =
        (0..offsets.len()).map(|i| format!("\"webpack://fixture/./src/module-{i}.ts\"")).collect();
    let mut mappings = String::new();
    let mut prev = 0u32;
    for (i, offset) in offsets.iter().enumerate() {
        if i > 0 {
            mappings.push(',');
        }
        // The first segment establishes the origin, so its source and line
        // deltas are zero; every later segment moves on by one. Hardcoding 1 for
        // the first segment too is what made an early version of this generator
        // produce a map that pointed one past its own sources array.
        let _ = write!(
            mappings,
            "{}{}{}{}",
            vlq(i64::from(*offset - prev)),
            vlq(i64::from(i > 0)),
            vlq(i64::from(i > 0)),
            vlq(0)
        );
        prev = *offset;
    }
    format!(
        r#"{{"version":3,"file":"bundle.js","sources":[{}],"sourcesContent":[],"names":[],"mappings":"{}"}}"#,
        sources.join(","),
        mappings
    )
    .into_bytes()
}

proptest! {
    /// Every generated byte *after the first mapping* is accounted for once.
    ///
    /// This is the property behind the "bytes after the last mapping" bug: the
    /// tail belongs to the last source, and the total has to come out at the
    /// real file size rather than at the last mapping's offset.
    ///
    /// The prologue (bytes before the first mapping) is deliberately left
    /// unattributed - see ttribute_by_source_in for why guessing it would be
    /// the unsafe direction.
    #[test]
    fn attribution_sums_to_the_generated_length(offsets in prop::collection::vec(0u32..50_000, 1..24)) {
        let mut sorted = offsets;
        sorted.sort_unstable();
        sorted.dedup();
        prop_assume!(sorted.len() >= 2);

        let generated = u64::from(sorted.last().copied().unwrap()) + 4_321;
        let map = parse_bytes(&map_with_segments(&sorted)).expect("valid map");

        let by_source = map.attribute_by_source_in(generated);
        let total: u64 = by_source.iter().map(|(_, bytes)| bytes).sum();
        let prologue = u64::from(sorted[0]);
        prop_assert_eq!(
            total,
            generated - prologue,
            "attributed {} of {} generated bytes ({} before the first mapping)",
            total,
            generated,
            prologue
        );

        // And no source is credited bytes it cannot own.
        for (index, bytes) in &by_source {
            prop_assert!(*index < sorted.len(), "source index {} out of range", index);
            prop_assert!(*bytes > 0, "a zero-byte source must not be listed");
        }
    }

    /// Decoded offsets are the cumulative sum of the encoded deltas.
    ///
    /// A sign error in the VLQ decoder shows up here and nowhere else: it would
    /// still produce a plausible-looking map.
    #[test]
    fn decoded_offsets_are_the_cumulative_deltas(
        deltas in prop::collection::vec(1u32..5_000, 1..20),
    ) {
        let mut offsets = Vec::with_capacity(deltas.len());
        let mut acc = 0u32;
        for d in &deltas {
            acc += d;
            offsets.push(acc);
        }
        let map = parse_bytes(&map_with_segments(&offsets)).expect("valid map");
        let decoded: Vec<u32> = map.mappings.iter().map(|m| m.generated_offset).collect();
        prop_assert_eq!(decoded, offsets);
        // offsets is compared by value above, so re-borrow for the window walk.
        // Offsets are non-decreasing, which the report relies on when it walks
        // windows(2) to attribute spans.
        for pair in map.mappings.windows(2) {
            prop_assert!(
                pair[0].generated_offset <= pair[1].generated_offset,
                "offsets must not go backwards: {} then {}",
                pair[0].generated_offset,
                pair[1].generated_offset
            );
        }
    }

    /// The path join is reflexive, and never matches a partial segment.
    ///
    /// `src/a` must not match `src/ab`: bundlers emit both, and matching them
    /// would attribute one module's bytes to another.
    #[test]
    fn suffix_matching_is_segment_aligned(path in "[a-zA-Z0-9_./-]{1,64}") {
        prop_assert!(suffix_match(&path, &path), "a path must match itself: {}", path);

        let stem = format!("{}-ish", path.trim_end_matches('/'));
        prop_assert!(
            !suffix_match(&stem, &path) || stem.ends_with(&path),
            "`{}` matched `{}` on a partial segment",
            stem,
            path
        );
    }

    /// A webpack-style URL and the same relative path are the same file.
    #[test]
    fn a_webpack_url_matches_its_relative_path(name in "[a-zA-Z0-9_.-]{1,24}") {
        let prefixed = format!("webpack://fixture/./src/{name}.ts");
        let relative = format!("./src/{name}.ts");
        prop_assert!(
            suffix_match(&relative, &prefixed),
            "`{}` should match `{}`",
            relative,
            prefixed
        );
    }
}

/// Size attribution scales declared sizes by what is really on disk, and the
/// graph says so.
///
/// The subtle part is the case where the measurement is *smaller* than the
/// bundler's claim: a minifier, a tree-shaken rebuild, or simply a stale stats
/// file. Scaling then legitimately produces a number below `stat`, which is
/// correct - but only if the graph is labelled `Parsed`, because a report that
/// presented it as the bundler's declared size would be wrong by 55 %.
#[test]
fn a_measurement_smaller_than_the_claim_is_still_labelled_parsed() {
    let dir = std::env::temp_dir().join("omnibundle-property-scaled");
    std::fs::create_dir_all(&dir).expect("temp dir");
    let on_disk = 400_000usize;
    std::fs::write(dir.join("main.js"), vec![b'x'; on_disk]).expect("write asset");
    let mut graph = UnifiedBundleGraph::new();
    graph.assets.push(Asset {
        name: "main.js".into(),
        size: on_disk as u64,
        chunks: vec![0],
        sizes: SizeSet { stat: 1_000_000, parsed: on_disk as u64, ..SizeSet::default() },
    });
    graph.chunks.push(Chunk {
        id: 0,
        names: vec!["main".into()],
        initial: true,
        assets: vec!["main.js".into()],
        size: SizeSet { stat: 1_000_000, ..SizeSet::default() },
    });
    graph.modules.insert(
        "./src/big.js".into(),
        Module {
            id: "./src/big.js".into(),
            name: "./src/big.js".into(),
            issuer: None,
            reasons: vec![],
            package: None,
            chunks: vec![0],
            sizes: SizeSet { stat: 900_000, ..SizeSet::default() },
            attribution_delta: 0,
            sources: vec![],
        },
    );

    sizes::attribute_from_disk(&mut graph, &dir).expect("the asset is on disk");

    let module = &graph.modules["./src/big.js"];
    // 400,000 / 1,000,000 of the declared 900,000.
    assert_eq!(module.sizes.parsed, 360_000, "scaled by the measured asset");
    assert!(module.sizes.parsed < module.sizes.stat);
    // The label is what stops the report from calling that a declared size.
    assert_eq!(graph.totals.size_dimension, SizeDimension::Parsed);

    // A missing asset is *not* an error - stats files list assets that were
    // cleaned up, and refusing to report in that case would make the tool
    // useless. What it must never be is a silent zero: the asset keeps its
    // declared size and says so.
    let empty = std::env::temp_dir().join("omnibundle-property-missing");
    std::fs::create_dir_all(&empty).expect("temp dir");
    // Fresh graph, so `parsed` starts unset the way an unattributed asset is.
    let mut graph2 = UnifiedBundleGraph::new();
    graph2.assets.push(Asset {
        name: "main.js".into(),
        size: 1_000_000,
        chunks: vec![0],
        sizes: SizeSet { stat: 1_000_000, ..SizeSet::default() },
    });
    graph2.chunks.push(Chunk {
        id: 0,
        names: vec!["main".into()],
        initial: true,
        assets: vec!["main.js".into()],
        size: SizeSet { stat: 1_000_000, ..SizeSet::default() },
    });
    sizes::attribute_from_disk(&mut graph2, &empty).expect("a missing asset is not fatal");
    let asset = graph2.assets.iter().find(|a| a.name == "main.js").expect("asset");
    // Nothing was measured, so `parsed` stays unset and `stat` still stands. A
    // zero here would be the treemap lying about where the bytes went.
    assert_eq!(asset.sizes.parsed, 0, "no measurement means no parsed size");
    assert_eq!(asset.sizes.stat, 1_000_000, "the declared size stands, not zero");
    let diagnostic = graph2
        .diagnostics
        .iter()
        .find(|d| d.code == "OB0002")
        .expect("a missing asset must be reported");
    assert_eq!(diagnostic.severity, Severity::Info, "it is not a build-breaking error");
}
/// A negative or corrupt generated delta must be rejected rather than wrapped.
///
/// Kept outside `proptest!` because that macro requires at least one strategy
/// parameter per function, and this one asserts a fixed property. It is here
/// because a wrapping cast in the decoder is invisible in the happy path: it
/// would produce a plausible map that mis-attributes every later byte.
#[test]
fn a_corrupt_delta_is_rejected_not_wrapped() {
    // "2gB" is a truncated continuation: the decoder must refuse rather than
    // invent an offset.
    let raw = br#"{"version":3,"file":"b.js","sources":["a.ts"],"names":[],"mappings":"2gB"}"#;
    match parse_bytes(raw) {
        Err(_) => {}
        Ok(map) => {
            for m in &map.mappings {
                assert!(
                    m.generated_offset < 1_000_000,
                    "a corrupt delta produced offset {}",
                    m.generated_offset
                );
            }
        }
    }

    // A well-formed map still parses after all that: the point is to reject the
    // corrupt input, not to become stricter than the format.
    let good = br#"{"version":3,"file":"b.js","sources":["a.ts"],"names":[],"mappings":"AAAA"}"#;
    assert!(parse_bytes(good).is_ok());
}
