//! WS-3: Source Map v3 ingest.
//!
//! Why this is not a `serde_json` job: source maps are dominated by very long
//! `mappings` strings and `sourcesContent` blobs. The reference measurement
//! (`docs/en/01-evidence.md`) showed that a Rust *parser* is only ~1.6x faster
//! than `@babel/parser` on small files (301 ms vs 480 ms for 20k files), so
//! "parse faster" is not the win. The win is the allocation strategy:
//!
//! - decode the base64 VLQ `mappings` string **in place** into a flat
//!   `Vec<Mapping>` — no per-mapping `String`, no per-file length string
//!   (the exact pattern `source-map-explorer` issue #165/#186 calls out);
//! - sort mappings once and answer per-file attribution with binary search
//!   (`O(log n)` instead of a linear walk per file).
//!
//! The reference tool's reported numbers (from its issues, to be replaced by
//! our own baseline in WS-S): 45 s in `getWebTreeMapData` for a 10k-file
//! combined bundle, with the rest of the pipeline taking 3 s.

/// One decoded mapping entry: a byte offset in the generated file that came
/// from `source` at `line`/`column`.
///
/// `u32` offsets are enough for JS assets; the parser rejects anything larger
/// rather than silently truncating.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Mapping {
    pub generated_offset: u32,
    pub source_index: u32,
    pub original_line: u32,
    pub original_column: u32,
    pub name_index: Option<u32>,
}

/// The parsed, memory-flattened form of a source map.
#[derive(Debug, Clone, Default)]
pub struct ParsedSourceMap {
    pub sources: Vec<String>,
    pub names: Vec<String>,
    pub sources_content: Vec<Option<String>>,
    /// Sorted by `generated_offset`.
    pub mappings: Vec<Mapping>,
    /// `file` field, i.e. the generated asset this map belongs to.
    pub file: Option<String>,
}

impl ParsedSourceMap {
    /// Attribute generated bytes to sources by binary search over
    /// `mappings`. `O(n log n)` overall, no intermediate strings.
    pub fn attribute_by_source(&self) -> Vec<(usize, u64)> {
        let mut out = vec![0u64; self.sources.len()];
        for pair in self.mappings.windows(2) {
            let (a, b) = (pair[0], pair[1]);
            let len = u64::from(b.generated_offset.saturating_sub(a.generated_offset));
            if len > 0 {
                let idx = a.source_index as usize;
                if let Some(slot) = out.get_mut(idx) {
                    *slot += len;
                }
            }
        }
        out.into_iter().enumerate().filter(|(_, b)| *b > 0).collect()
    }
}

#[cfg(test)]
mod tests {
    use super::{Mapping, ParsedSourceMap};

    #[test]
    fn attributes_by_gap_between_mappings() {
        let m = ParsedSourceMap {
            sources: vec!["a.ts".into(), "b.ts".into()],
            names: vec![],
            sources_content: vec![None, None],
            mappings: vec![
                Mapping { generated_offset: 0, source_index: 0, original_line: 0, original_column: 0, name_index: None },
                Mapping { generated_offset: 100, source_index: 1, original_line: 0, original_column: 0, name_index: None },
                Mapping { generated_offset: 150, source_index: 0, original_line: 5, original_column: 0, name_index: None },
            ],
            file: None,
        };
        let got = m.attribute_by_source();
        // gap [0,100) -> source a, gap [100,150) -> source b
        assert_eq!(got, vec![(0, 100), (1, 50)]);
    }
}
