//! WS-4: the fusion engine — this is `OmniBundle`'s actual differentiator.
//!
//! Given a stats graph and one or more source maps, produce one graph whose
//! sizes are ground truth, plus two diagnostics the reference tools cannot
//! produce:
//!
//! - **ghost code**: declared by the bundler, accounted for by no mapping.
//!   Either tree-shaking did not drop it, or the asset was built without a map.
//! - **hidden code**: generated bytes that map back to no module — inlined
//!   snippets, `eval`, runtime shims, injected polyfills.
//!
//! Invariants the CLI enforces before writing a report (see
//! `check_size_invariant` in `crate::model`):
//! 1. `sum(module.effective) == total` within the tolerance in the report
//!    contract (0.1%).
//! 2. every `GhostModule.module` exists in `modules`.
//! 3. `total_attribution_delta == sum(module.attribution_delta)`.

use crate::model::{GhostReason, SizeDimension};

/// Why a module is considered a ghost. The rule set lives here so both the
/// CLI and the tests share one definition.
pub fn classify_ghost(
    declared_size: u64,
    attributed_size: Option<u64>,
    asset_present: bool,
) -> Option<GhostReason> {
    if !asset_present {
        return Some(GhostReason::MissingAsset);
    }
    match attributed_size {
        None => Some(GhostReason::Unmapped),
        Some(0) if declared_size > 0 => Some(GhostReason::EmptyAttribution),
        _ => None,
    }
}

/// The size dimension a fused graph should report.
///
/// Only switch to `Attributed` when every asset that contributes bytes is
/// covered by a map; a partial map would otherwise make the report look
/// smaller than reality, which is the worst possible bug for this tool.
pub fn choose_dimension(
    mapped_assets: usize,
    total_assets: usize,
) -> SizeDimension {
    if total_assets > 0 && mapped_assets == total_assets {
        SizeDimension::Attributed
    } else {
        SizeDimension::Parsed
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn missing_asset_beats_everything() {
        assert_eq!(classify_ghost(10, None, false), Some(GhostReason::MissingAsset));
    }

    #[test]
    fn unmapped_and_empty_are_distinguished() {
        assert_eq!(classify_ghost(10, None, true), Some(GhostReason::Unmapped));
        assert_eq!(classify_ghost(10, Some(0), true), Some(GhostReason::EmptyAttribution));
        assert_eq!(classify_ghost(10, Some(10), true), None);
    }

    #[test]
    fn partial_coverage_never_reports_attributed() {
        use crate::model::SizeDimension::*;
        assert_eq!(choose_dimension(3, 4), Parsed);
        assert_eq!(choose_dimension(4, 4), Attributed);
        assert_eq!(choose_dimension(0, 0), Parsed);
    }
}
